export default [{
	"id": "1",
	"pdImg": "../../static/img/pdlist/list2.jpg",
	"pdName": "NGA玩家社区2019下半年公开集中版主招募公告",
	"pdPrice": 1149.00,
	"pdSold": 648,
	"pdTitle": "议事厅"
}, {
	"id": "2",
	"pdImg": "../../static/img/pdlist/list0.jpg",
	"pdName": "魔兽世界8.3和第四赛季启动页预览",
	"pdPrice": 89.00,
	"pdSold": 128,
	"pdTitle": "往事杂谈"
}, {
	"id": "3",
	"pdImg": "../../static/img/pdlist/list1.jpg",
	"pdName": "魔兽测试服附魔幻象:虚空之锋来源及预览",
	"pdPrice": 195.00,
	"pdSold": 968,
	"pdTitle": "议事厅"
}, {
	"id": "4",
	"pdImg": "../../static/img/pdlist/list3.jpg",
	"pdName": "深圳阴阳师快闪餐厅体验",
	"pdPrice": 299.00,
	"pdSold": 85,
	"pdTitle": "阴阳师"
}, {
	"id": "5",
	"pdImg": "../../static/img/pdlist/list4.png",
	"pdName": "EPL S10总决赛赛程对阵公布",
	"pdPrice": 1889.00,
	"pdSold": 18,
	"pdTitle": "王者荣耀"
}, {
	"id": "6",
	"pdImg": "../../static/img/pdlist/list5.png",
	"pdName": "梦归奇迹 英雄梯度排行 第十四期",
	"pdPrice": 70.00,
	"pdSold": 658,
	"pdTitle": "梦幻西游"
}, {
	"id": "7",
	"pdImg": "../../static/img/pdlist/list6.jpg",
	"pdName": "魔兽世界8.3新版本主线再说啥",
	"pdPrice": 268.00,
	"pdSold": 128,
	"pdTitle": "议事厅"
}, {
	"id": "8",
	"pdImg": "../../static/img/pdlist/list7.jpg",
	"pdName": "阴阳师百鬼奕丝滑12连胜",
	"pdPrice": 140.00,
	"pdSold": 366,
	"pdTitle": "阴阳师"
}, {
	"id": "9",
	"pdImg": "../../static/img/pdlist/list8.jpg",
	"pdName": "S10季前具体时间安排 冠军杯赛全球开启测试",
	"pdPrice": 252.00,
	"pdSold": 98,
	"pdTitle": "英雄联盟"
}, {
	"id": "10",
	"pdImg": "../../static/img/pdlist/list9.jpg",
	"pdName": "魔兽世界8.2.5永恒王宫火法FARM心得浅谈",
	"pdPrice": 89.00,
	"pdSold": 128,
	"pdTitle": "议事厅"
}]
